//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellersDB
    {
        public int SellerID { get; set; }
        public string FIOSeller { get; set; }
        public string ViewTovarSeller { get; set; }
        public string PhoneSeller { get; set; }
    }
}
