//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersDB
    {
        public int ID { get; set; }
        public int id_tovar { get; set; }
        public int id_manager { get; set; }
        public decimal Pricetovar { get; set; }
        public decimal Koltovar { get; set; }
    
        public virtual MenegersDB MenegersDB { get; set; }
        public virtual TovarDB TovarDB { get; set; }
    }
}
